main_app/urls.py
from django.urls import path
from . import views
# from main_app.views import WidgetList

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

      # route for widget index
    path('widgets/', views.widgets_index, name='index'),
    # path('widgets/', views.WidgetList.as_view(), name='index'), #WTF?
    
    path('widgets/<int:widget_id>/', views.widgets_detail, name='detail'),
    path('widgets/create/', views.WidgetCreate.as_view(), name='widget_create'),
    path('widgets/<int:pk>/update/', views.WidgetUpdate.as_view(), name='widgets_update'),
    path('widgets/<int:pk>/delete/', views.WidgetDelete.as_view(), name='widgets_delete'),
    path('widgets/<int:widget_id>/add_cleaning/', views.add_cleaning, name='add_cleaning'),

    path('accessories/', views.AccessoryList.as_view(), name='accessories_index'),
    path('accessories/<int:pk>/', views.AccessoryDetail.as_view(), name='accessories_detail'),
    path('accessories/create/', views.AccessoryCreate.as_view(), name='accessories_create'),
    path('accessories/<int:pk>/update/', views.AccessoryUpdate.as_view(), name='accessories_update'),
    path('accessories/<int:pk>/delete/', views.AccessoryDelete.as_view(), name='accessories_delete'),
    path('accessories/<int:widget_id>/assoc_accessory/<int:accessory_id>/', views.assoc_accessory, name='assoc_accessory'),
]

widgetcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

CLEANING = (
  ('D', 'Dusting'),
  ('V', 'Vacuuming'),
  ('B', 'Dusting & Vacuuming'),
)

# Create your models here.

class Accessory(models.Model):
  name = models.CharField(max_length=50)
  function = models.CharField(max_length=100)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('accessories_detail', kwargs={'pk': self.id})
  
class Widget(models.Model): 
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    price = models.IntegerField()
    accessories = models.ManyToManyField(Accessory)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'widget_id':self.id})
 
class Cleaning(models.Model):
    date = models.DateField()
    c_type = models.CharField(
        'cleaning type',
        max_length=1,
        choices=CLEANING,
        default=CLEANING[2][0],
        )
    widget = models.ForeignKey(Widget, on_delete=models.CASCADE)    
    
    def __str__(self):
        return f"{self.get_c_type_display()} on {self.date}"
    
    # change the default sort
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Cleaning

class CleaningForm(ModelForm):
  class Meta:
    model = Cleaning
    fields = ['date', 'c_type']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Widget, Accessory
from .forms import CleaningForm

# fake data for testing
# class Widget: 
#   def __init__(self, name, type, description, price):
#     self.name = name
#     self.type = type
#     self.description = description
#     self.price = price

# widgets = [
#   Widget('Thing 1', 'object', '6 sided cube', 3),
#   Widget('Thing 2', 'consumer item', 'fidget spinner', 5),
#   Widget('Thing 3', 'business item', 'pencil sharpener', 23)
# ]


# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

# Add new view
def widgets_index(request):
    widgets = Widget.objects.all()
    return render(request, 'widgets/index.html', { 'widgets': widgets })

# class WidgetList(ListView):
#     model = Widget
#     template_name = 'widgets/index.html'

#     def get_queryset(self):
#       # print('st88ff: ', Widget.objects.all())
#       widgets = Widget.objects.all()
#       return widgets

def widgets_detail(request, widget_id):
    widget = Widget.objects.get(id=widget_id)
    id_list = widget.accessories.all().values_list('id')
    accessories_widget_doesnt_have = Accessory.objects.exclude(id__in=id_list)
    cleaning_form = CleaningForm()
    return render(request, 'widgets/detail.html', { 
      'widget': widget, 
      'cleaning_form' : cleaning_form, 
      'accessories' : accessories_widget_doesnt_have,
    })
class WidgetCreate(CreateView):
  model = Widget
  fields = ['name', 'type', 'description', 'price']
  success_url = '/widgets/'

class WidgetUpdate(UpdateView):
  model = Widget
  # Let's disallow the renaming by excluding the name field!
  fields = ['type', 'description', 'price']

class WidgetDelete(DeleteView):
  model = Widget
  success_url = '/widgets/'

def add_cleaning(request, widget_id):
    # create a ModelForm instance using the data in request.POST
  form = CleaningForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it has widget_id assigned
    new_cleaning = form.save(commit=False)
    new_cleaning.widget_id = widget_id
    new_cleaning.save()
  return redirect('detail', widget_id=widget_id)
    
def assoc_accessory(request, widget_id, accessory_id):
  # Note that you can pass a accessories id instead of the whole accessory object
  Widget.objects.get(id=widget_id).accessories.add(accessory_id)
  return redirect('detail', widget_id=widget_id)

class AccessoryList(ListView):
  model = Accessory

class AccessoryDetail(DetailView):
  model = Accessory

class AccessoryCreate(CreateView):
  model = Accessory
  fields = '__all__'

class AccessoryUpdate(UpdateView):
  model = Accessory
  fields = ['name', 'function']

class AccessoryDelete(DeleteView):
  model = Accessory
  success_url = '/accessories/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Widget Collector</h1>
<hr />
<p>Hire the Widget Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Widgets Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;WidgetCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'widget_create' %}">Add a Widget</a></li>
          <li><a href="{% url 'index' %}">View All My Widgets</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Widget Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>All things Widgets!</h1>

{% endblock %}

main_app/templates/main_app/widget_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Widget</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn"> &nbsp;
    <a href="{% url 'detail' widget.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/widget_form.html
{% extends 'base.html' %}

{% block content %}
    {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
    {% else %}
    <h1>Add Widget</h1>
    {% endif %}
    
    <!-- Leaving the action empty makes the form post to the same url used to display it -->
    <form action="" method="POST">
        <!-- Django requires the following for security purposes -->
        {% csrf_token %}
        <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit!" class="btn">
    </form>
{% endblock %}

main_app/templates/main_app/widget_list.html
<!-- Not needed? -->

main_app/templates/widgets/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Widget Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ widget.name }}</span>
        <p>Type: {{ widget.type }}</p>
        <p>Description: {{ widget.description|linebreaks }}</p>
        <p>Age: {{ widget.price }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'widgets_update' widget.id %}">Edit</a>
        <a href="{% url 'widgets_delete' widget.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_cleaning' widget.id %}" method="POST">
      {% csrf_token %}
      {{ cleaning_form.as_p }}
      <input type="submit" class="btn" value="Add Cleaning">
    </form>
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Cleaning Type</th></tr>
      </thead>
      <tbody>
        {% for cleaning in widget.cleaning_set.all %}
          <tr>
            <td>{{cleaning.date}}</td>
            <td>{{cleaning.get_c_type_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ widget.name }}'s Accessories</h3>
      {% if widget.accessories.count %}
        {% for accessory in widget.accessories.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A {{ accessory.name }} that {{ accessory.function }}
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Accessories :(</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Accessories</h3>
      {% if accessories.count %}
        {% for accessory in accessories.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A {{ accessory.name }} that {{ accessory.function }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_accessory' widget.id accessory.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{widget.name}} Already Has All Available Accessories</h5>
      {% endif %}
    </div>
  </div>
  
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_c_type');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/widgets/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Widget List</h1>

{% for widget in widgets %}
  <div class="card">
    <a href="{% url 'detail' widget.id %}">
    <div class="card-content">
      <span class="card-title">{{ widget.name }}</span>
      <p>Type: {{ widget.type }}</p>
      <p>Description: {{ widget.description|linebreaks }}</p>
      <p>Price: {{ widget.price }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}